/*
SQLyog Trial v12.14 (32 bit)
MySQL - 5.7.11 : Database - XZ_PRODUCT
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `XZ_PICTURE` */

DROP TABLE IF EXISTS `XZ_PICTURE`;

CREATE TABLE `XZ_PICTURE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MD5_HASH` varchar(32) DEFAULT NULL,
  `UPLOAD_CDN` tinyint(1) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  `CDN_URL` varchar(255) DEFAULT NULL,
  `PATH` varchar(500) DEFAULT NULL,
  `ORIGINAL_ID` int(11) DEFAULT NULL,
  `CROP_SIZE` varchar(100) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU` */

DROP TABLE IF EXISTS `XZ_SKU`;

CREATE TABLE `XZ_SKU` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `CATEGORY_ID` int(11) DEFAULT NULL,
  `SKU_EXT_CODE` varchar(50) DEFAULT NULL,
  `SUPPLIER_CODE` varchar(50) DEFAULT NULL,
  `INVENTORY` int(11) DEFAULT NULL,
  `UNLIMITED_INVENTORY` tinyint(1) DEFAULT NULL,
  `IS_SIMPLE` tinyint(1) DEFAULT NULL,
  `ALLOCATION` varchar(10) DEFAULT NULL,
  `VISIBILITY` varchar(20) DEFAULT NULL,
  `MAINTENANCE_TIME` int(11) DEFAULT NULL,
  `ALIAS_TO` int(11) DEFAULT NULL,
  `PRICE_PER` varchar(20) DEFAULT NULL,
  `DEFAULT_CALENDAR_STATUS` varchar(10) DEFAULT NULL,
  `START_PRICE` decimal(8,2) DEFAULT NULL,
  `PKG_START_PRICE` decimal(8,2) DEFAULT NULL,
  `SKU_GROUPING` varchar(10) DEFAULT NULL,
  `SKU_PARENT_CHILD` varchar(10) DEFAULT NULL,
  `LIST_IMAGE` varchar(255) DEFAULT NULL,
  `SORT` int(11) DEFAULT NULL,
  `SKU_STATUS` int(11) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DELETE_TIME` timestamp ,
  `IS_DELETED` tinyint(1) DEFAULT NULL,
  `DATE_INVENTORY_CONTROL` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=142 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_ALLOCATION` */

DROP TABLE IF EXISTS `XZ_SKU_ALLOCATION`;

CREATE TABLE `XZ_SKU_ALLOCATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `ALLOCATION` varchar(10) DEFAULT NULL,
  `FIXED_LENGTH` int(11) DEFAULT NULL,
  `FIXED_START_TIME` varchar(10) DEFAULT NULL,
  `DEFAULT_LENGTH` int(11) DEFAULT NULL,
  `UNIT` varchar(10) DEFAULT NULL,
  `BOOKING_DISPLAY` varchar(10) DEFAULT NULL,
  `SHOW_END_TIMES` smallint(6) DEFAULT NULL,
  `SHOW_UNAVAILABLE_SLOTS` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=76 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_ALLOCATION_TIMESLOT` */

DROP TABLE IF EXISTS `XZ_SKU_ALLOCATION_TIMESLOT`;

CREATE TABLE `XZ_SKU_ALLOCATION_TIMESLOT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `ALLOCATION_ID` int(11) DEFAULT NULL,
  `START_TIME` varchar(20) DEFAULT NULL,
  `END_TIME` varchar(20) DEFAULT NULL,
  `DAY_OF_WEEK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=220 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_ATTR` */

DROP TABLE IF EXISTS `XZ_SKU_ATTR`;

CREATE TABLE `XZ_SKU_ATTR` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `DEFAULT_VALUE` int(11) DEFAULT NULL,
  `HAS_PRICE` tinyint(1) DEFAULT NULL,
  `IS_DISPLAY_RANGE` tinyint(1) DEFAULT NULL,
  `IS_CTRL_INVENTORY` tinyint(1) DEFAULT NULL,
  `IS_REQUIRED` tinyint(1) DEFAULT NULL,
  `VISIBILITY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=248 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_ATTR_APPLY_TO` */

DROP TABLE IF EXISTS `XZ_SKU_ATTR_APPLY_TO`;

CREATE TABLE `XZ_SKU_ATTR_APPLY_TO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `SKU_ATTR_ID` int(11) DEFAULT NULL,
  `MIN_NUM` int(11) DEFAULT NULL,
  `MAX_NUM` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=103 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_ATTR_I18N` */

DROP TABLE IF EXISTS `XZ_SKU_ATTR_I18N`;

CREATE TABLE `XZ_SKU_ATTR_I18N` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ATTR_ID` int(11) DEFAULT NULL,
  `LANGUAGE` varchar(10) DEFAULT NULL,
  `PARAMS` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_CATEGORY` */

DROP TABLE IF EXISTS `XZ_SKU_CATEGORY`;

CREATE TABLE `XZ_SKU_CATEGORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `CATEGORY_NAME` varchar(50) DEFAULT NULL,
  `CATEGORY_IMG` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `SORT` int(11) DEFAULT NULL,
  `CREATE_USER` int(11) DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1111129 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_DYNC_PROP` */

DROP TABLE IF EXISTS `XZ_SKU_DYNC_PROP`;

CREATE TABLE `XZ_SKU_DYNC_PROP` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `ATTR_DEF_ID` int(11) DEFAULT NULL,
  `ATTR_VALUE` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_I18N` */

DROP TABLE IF EXISTS `XZ_SKU_I18N`;

CREATE TABLE `XZ_SKU_I18N` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `SKU_TITLE` varchar(300) DEFAULT NULL,
  `SUMMARY` varchar(500) DEFAULT NULL,
  `DETAILS` text,
  `LOCATION` varchar(200) DEFAULT NULL,
  `MARKER_TITLE` varchar(50) DEFAULT NULL,
  `MARKER_DESCRIPTION` varchar(200) DEFAULT NULL,
  `MARKER_LINK_TEXT` varchar(50) DEFAULT NULL,
  `MAP_ZOOM` int(11) DEFAULT NULL,
  `LANGUAGE` varchar(10) DEFAULT NULL,
  `EMAIL_NOTIFICATION` varchar(2000) DEFAULT NULL,
  `MORE_INFO_URL` varchar(200) DEFAULT NULL,
  `VIDEO_URL` varchar(255) DEFAULT NULL,
  `VIDEO_START_TIME` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_IMAGE` */

DROP TABLE IF EXISTS `XZ_SKU_IMAGE`;

CREATE TABLE `XZ_SKU_IMAGE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `PICTURE_ID` int(11) DEFAULT NULL,
  `PICTURE_URL` varchar(255) DEFAULT NULL,
  `CAPTION` varchar(20) DEFAULT NULL,
  `SORT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_INVENTORY` */

DROP TABLE IF EXISTS `XZ_SKU_INVENTORY`;

CREATE TABLE `XZ_SKU_INVENTORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `SELL_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `INVENTORY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PKG` */

DROP TABLE IF EXISTS `XZ_SKU_PKG`;

CREATE TABLE `XZ_SKU_PKG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `SKU_TITLE` varchar(300) DEFAULT NULL,
  `PACKAGE_TYPE` varchar(10) DEFAULT NULL,
  `PACKAGE_SKU_ID` int(11) DEFAULT NULL,
  `PACKAGE_IN_TYPE` varchar(10) DEFAULT NULL,
  `PACKAGE_PRICE_PERCENTAGE` int(11) DEFAULT NULL,
  `PRICE` double(7,2) DEFAULT NULL COMMENT '浜у搧鍘熶环',
  `TOGETHERPRICE` double(7,2) DEFAULT NULL COMMENT '涓�捣涔颁紭鎯犱环',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PKG_ATTR_MAPPING` */

DROP TABLE IF EXISTS `XZ_SKU_PKG_ATTR_MAPPING`;

CREATE TABLE `XZ_SKU_PKG_ATTR_MAPPING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `PACKAGE_ID` int(11) DEFAULT NULL,
  `SKU_ATTR_ID` int(11) DEFAULT NULL,
  `PKG_SKU_ATTR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PRICE_BASE` */

DROP TABLE IF EXISTS `XZ_SKU_PRICE_BASE`;

CREATE TABLE `XZ_SKU_PRICE_BASE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `BOOKING_PRICE_TYPE` varchar(20) DEFAULT NULL,
  `SKU_PARAMS_ID` int(11) DEFAULT NULL,
  `PRICE` decimal(8,2) DEFAULT NULL,
  `BOOKING_PRICE_UNIT` varchar(50) DEFAULT NULL,
  `IS_GROUP` smallint(6) DEFAULT NULL,
  `MIN_NUMBER` int(11) DEFAULT NULL,
  `MAX_NUMBER` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1111350 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PRICE_EVENT` */

DROP TABLE IF EXISTS `XZ_SKU_PRICE_EVENT`;

CREATE TABLE `XZ_SKU_PRICE_EVENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `EVENT_NAME` varchar(20) DEFAULT NULL,
  `EVENT_TYPE` varchar(20) DEFAULT NULL,
  `PRICE_TYPE` varchar(10) DEFAULT NULL,
  `START_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `END_DATE` timestamp ,
  `APPLICABLE_DAYS` int(11) DEFAULT NULL,
  `APPLICABLE_TIME` varchar(200) DEFAULT NULL,
  `DYNAMIC_PRICE_TYPE` varchar(10) DEFAULT NULL,
  `DYNAMIC_PRICE_VALUE` varchar(20) DEFAULT NULL,
  `RULESET` int(11) DEFAULT NULL,
  `INVENTORY_STATUS` tinyint(1) DEFAULT NULL,
  `RECURRENCE` varchar(10) DEFAULT NULL,
  `APPLY_ALL` tinyint(1) DEFAULT NULL,
  `PRICE` double(7,2) DEFAULT NULL COMMENT '浜嬩欢璁＄畻鍚庣殑浠锋牸',
  `WEIGHT` tinyint(2) DEFAULT NULL COMMENT '鏉冮噸',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4444590 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PRICE_EVENT_APPLY_TO` */

DROP TABLE IF EXISTS `XZ_SKU_PRICE_EVENT_APPLY_TO`;

CREATE TABLE `XZ_SKU_PRICE_EVENT_APPLY_TO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `EVENT_ID` int(11) DEFAULT NULL,
  `TARGET_ID` int(11) DEFAULT NULL,
  `APPLY_TO_TYPE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PRICE_EVENT_NEW_PRICE` */

DROP TABLE IF EXISTS `XZ_SKU_PRICE_EVENT_NEW_PRICE`;

CREATE TABLE `XZ_SKU_PRICE_EVENT_NEW_PRICE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `EVENT_ID` int(11) DEFAULT NULL,
  `PARAMS_ID` int(11) DEFAULT NULL,
  `EVENT_PRICE` decimal(8,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PRICE_EVENT_RULES` */

DROP TABLE IF EXISTS `XZ_SKU_PRICE_EVENT_RULES`;

CREATE TABLE `XZ_SKU_PRICE_EVENT_RULES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `RULES_NAME` varchar(20) DEFAULT NULL,
  `MAX_DURATION` int(11) DEFAULT NULL,
  `MIN_DURATION` int(11) DEFAULT NULL,
  `MAX_BOOKING` int(11) DEFAULT NULL,
  `MIN_BOOKING` int(11) DEFAULT NULL,
  `DAY_OF_WEEK` int(11) DEFAULT NULL,
  `CUTOFF` int(11) DEFAULT NULL,
  `OVERBOOKING_ALLOWANCE` int(11) DEFAULT NULL,
  `FORWARD_BOOKING_WINDOW` int(11) DEFAULT NULL,
  `PAST_BOOKING_WINDOW` int(11) DEFAULT NULL,
  `MAX_MEONY` varchar(20) DEFAULT NULL,
  `MIN_MONEY` varchar(20) DEFAULT NULL,
  `MAX_DURATION_APPLY_TO` varchar(20) DEFAULT NULL,
  `MIN_DURATION_APPLY_TO` varchar(20) DEFAULT NULL,
  `MAX_BOOKING_APPLY_TO` varchar(20) DEFAULT NULL,
  `MIN_BOOKING_APPLY_TO` varchar(20) DEFAULT NULL,
  `DAY_OF_WEEK_APPLY_TO` varchar(20) DEFAULT NULL,
  `CUTOFF_APPLY_TO` varchar(20) DEFAULT NULL,
  `OVERBOOKING_ALLOWANCE_APPLY_TO` varchar(20) DEFAULT NULL,
  `FORWARD_BOOKING_WINDOW_APPLY_TO` varchar(20) DEFAULT NULL,
  `PAST_BOOKING_WINDOW_APPLY_TO` varchar(20) DEFAULT NULL,
  `MAX_MEONY_APPLY_TO` varchar(20) DEFAULT NULL,
  `MIN_MONEY_APPLY_TO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=333459 DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SKU_PRICE_EVENT_TIMESLOT` */

DROP TABLE IF EXISTS `XZ_SKU_PRICE_EVENT_TIMESLOT`;

CREATE TABLE `XZ_SKU_PRICE_EVENT_TIMESLOT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BOSSID` int(11) DEFAULT NULL,
  `SKU_ID` int(11) DEFAULT NULL,
  `EVENT_ID` int(11) DEFAULT NULL,
  `TIMESLOT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SYSTEM_STRING` */

DROP TABLE IF EXISTS `XZ_SYSTEM_STRING`;

CREATE TABLE `XZ_SYSTEM_STRING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PAGE` varchar(50) DEFAULT NULL,
  `STR_KEY` varchar(50) DEFAULT NULL,
  `STR_VAL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `XZ_SYSTEM_STRING_I18N` */

DROP TABLE IF EXISTS `XZ_SYSTEM_STRING_I18N`;

CREATE TABLE `XZ_SYSTEM_STRING_I18N` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LANGUAGE` varchar(10) DEFAULT NULL,
  `STR_KEY` varchar(50) DEFAULT NULL,
  `STR_VAL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
