ALTER TABLE `TICKETRULE`
ADD COLUMN `CREATEDATE`  TIMESTAMP  NULL DEFAULT NULL COMMENT '创建时间' AFTER `exchangeValue`,
ADD COLUMN `UPDATEDATE`  TIMESTAMP  NULL DEFAULT NULL COMMENT '创建时间' AFTER `CREATEDATE`;
