DELETE FROM `core_deploment`.`product_dict` WHERE `id`='31';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='32';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='33';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='34';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='35';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='36';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='37';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='38';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='39';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='40';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='41';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='42';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='43';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='44';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='45';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='46';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='47';
DELETE FROM `core_deploment`.`product_dict` WHERE `id`='48';
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('31', '普通票', '1', 'product:procategory', '产品分类', '1', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('32', '剧场', '10', 'product:procategory', '产品分类', '2', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('33', '定向返利产品', '4', 'product:procategory', '产品分类', '3', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('34', '普通票联票子票', '5', 'product:procategory', '产品分类', '4', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('35', '组合票', '11', 'product:procategory', '产品分类', '5', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('36', '积分票联票子票', '12', 'product:procategory', '产品分类', '6', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('37', '演艺联票子票', '13', 'product:procategory', '产品分类', '7', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('38', '旅游产品', '14', 'product:procategory', '产品分类', '8', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('39', '小交通', '16', 'product:procategory', '产品分类', '9', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('40', '一日游 ', '17', 'product:procategory', '产品分类', '10', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('41', '线路', '1000', 'product:procategory', '产品分类', '11', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('42', '旅拍', '7000', 'product:procategory', '产品分类', '12', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('43', '包车', '4002', 'product:procategory', '产品分类', '13', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('44', '班车', '4001', 'product:procategory', '产品分类', '14', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('45', '特产', '5000', 'product:procategory', '产品分类', '15', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('46', '导游', '8000', 'product:procategory', '产品分类', '16', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('47', '住宿', '9', 'product:procategory', '产品分类', '17', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `sort`, `create_by`, `flag`) VALUES ('48', '特色餐饮', '9000', 'product:procategory', '产品分类', '18', 'admin', '1');
