START TRANSACTION;

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (1, '线上', '1', 'product:ticketTies', '票种', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (2, '线下', '0', 'product:ticketTies', '票种', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (20, '团票', '1', 'product:ticketvarie', '票品', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (21, '散票', '0', 'product:ticketvarie', '票品', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (31, '普通票', '1', 'product:procategory', '产品分类', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (32, '演艺票', '10', 'product:procategory', '产品分类', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (33, '积分票', '4', 'product:procategory', '产品分类', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (34, '普通票联票', '5', 'product:procategory', '产品分类', 4, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (35, '积分票联票', '12', 'product:procategory', '产品分类', 5, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (50, '成人', '1', 'product:ticketType', '票型', 1, NULL, NULL, '1', '2015-12-4 10:10:09', '票型dd', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (51, '儿童', '2', 'product:ticketType', '票型', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (52, '优惠', '3', 'product:ticketType', '票型', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (53, '老人', '4', 'product:ticketType', '票型', 4, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (70, '直营线下渠道', '1', 'product:sellingtool', '直销工具类型', 4, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (71, '员工微店', '2', 'product:sellingtool', '直销工具类型', 1, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (72, '直营线上渠道', '3', 'product:sellingtool', '直销工具类型', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (73, '线上自营微店渠道', '4', 'product:sellingtool', '直销工具类型', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (80, '团进团出', '1', 'product:checkInType', '团票检票方式', 1, NULL, NULL, NULL, NULL, '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (81, '非团进团出', '2', 'product:checkInType', '团票检票方式', 2, NULL, NULL, NULL, NULL, '', '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (90, '手持设备', '1', 'product:deviceType', '设备类型', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (91, '台式设备', '2', 'product:deviceType', '设备类型', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (92, '闸机', '3', 'product:deviceType', '设备类型', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (100, 'AAAAA', '1', 'product:scenicLevel', '景区等级', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (101, 'AAAA', '2', 'product:scenicLevel', '景区等级', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (102, 'AAA', '3', 'product:scenicLevel', '景区等级', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (103, 'AA', '4', 'product:scenicLevel', '景区等级', 4, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (104, 'A', '5', 'product:scenicLevel', '景区等级', 5, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (105, '非A', '6', 'product:scenicLevel', '景区等级', 6, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (120, '身份证', '1', 'product:pattern', '验票凭证', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (121, 'channelType3-1', '2', 'product:pattern', '验票凭证', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (122, '指纹', '3', 'product:pattern', '验票凭证', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (130, '普通用户', '1', 'user:type', '用户类型', 1, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (131, '旅行社', '2', 'user:type', '用户类型', 2, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (132, '旅行社部门', '3', 'user:type', '用户类型', 3, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (133, '导游', '4', 'user:type', '用户类型', 4, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (134, '商户', '5', 'user:type', '用户类型', 5, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (135, '分销商', '6', 'user:type', '用户类型', 6, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (136, '供应商', '7', 'user:type', '用户类型', 7, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (137, 'OTA', '8', 'user:type', '用户类型', 8, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (138, '票之家', '9', 'user:type', '用户类型', 9, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (150, '旅行社', '1', 'channel:channeltype', '渠道类别', 1, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (151, '导游', '2', 'channel:channeltype', '渠道类别', 2, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (152, '旅行社部门', '3', 'channel:channeltype', '渠道类别', 3, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (153, 'OTA', '4', 'channel:channeltype', '渠道类别', 4, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (154, '商户', '5', 'channel:channeltype', '渠道类别', 5, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (155, '魔方旅游', '0', 'channel:channeltype', '渠道类别', 6, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (170, '停用', '0', 'user:statusType', '状态类别', 1, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (171, '开启', '1', 'user:statusType', '状态类别', 2, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (172, '逻辑删除', '2', 'user:statusType', '状态类别', 3, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (173, '通过、同意', '3', 'user:statusType', '状态类别', 4, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (174, '拒绝', '4', 'user:statusType', '状态类别', 5, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (175, '待审核', '5', 'user:statusType', '状态类别', 6, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (176, '注册未完成', '6', 'user:statusType', '状态类别', 7, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (180, '直销', '1', 'channel:type', '直销渠道', 1, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (181, '分销', '2', 'channel:type', '直销渠道', 2, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (190, '支撑平台', '1', 'user:datasource', '用户类型', 1, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (191, '代供销平台', '2', 'user:datasource', '所属平台', 2, '0000-0-0 00:00:00', '', '', '0000-0-0 00:00:00', '', '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (192, '客栈', '3', 'user:datasource', '所属平台', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (193, '景区', '4', 'user:datasource', '所属平台', 4, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (194, '旅行社', '5', 'user:datasource', '所属平台', 5, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (195, '部门', '6', 'user:datasource', '所属平台', 6, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (196, '导游', '7', 'user:datasource', '所属平台', 7, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (197, '商户', '8', 'user:datasource', '所属平台', 8, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (210, '注册未完成', '0', 'user:userstatus', '用户注册状态', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (211, '审核通过', '1', 'user:userstatus', '用户注册状态', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (212, '审核拒绝，重新提交', '2', 'user:userstatus', '用户注册状态', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (213, '注册完成待审核', '3', 'user:userstatus', '用户注册状态', 4, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (220, '旅行社', '2', 'user:reselltype', '分销商类型', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (221, '旅行社部门', '3', 'user:reselltype', '分销商类型', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (222, '商户', '5', 'user:reselltype', '分销商类型', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (223, 'OTA', '8', 'user:reselltype', '分销商类型', 4, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (230, '当日', '1', 'channel:useperiod', '政策使用有效期', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (231, '产品有效期内', '0', 'channel:useperiod', '政策使用有效期', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (240, '存在加点返利', '1', 'channel:haveExtraRebateType', '是否存在加点返利', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (241, '不存在加点返利', '0', 'channel:haveExtraRebateType', '是否存在加点返利', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (250, '周一', '1', 'strategy:scope', '政策适用日期', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (251, '周二', '2', 'strategy:scope', '政策适用日期', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (252, '周三', '3', 'strategy:scope', '政策适用日期', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (253, '周四', '4', 'strategy:scope', '政策适用日期', 4, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (254, '周五', '5', 'strategy:scope', '政策适用日期', 5, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (255, '周六', '6', 'strategy:scope', '政策适用日期', 6, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (256, '周日', '7', 'strategy:scope', '政策适用日期', 7, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (260, '现金返利', '0', 'channel:rebatemethod', '返利形式', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (261, '定向票返利', '1', 'channel:rebatemethod', '返利形式', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (262, '返利积分', '2', 'channel:rebatemethod', '返利形式', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (270, '前返', '1', 'channel:rebatetype', '返利类型', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (271, '后返', '2', 'channel:rebatetype', '返利类型', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (281, '旅行社', 'H', 'channel:rebateobject', '返利对象', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (282, '旅行社部门', 'DH', 'channel:rebateobject', '返利对象', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (283, '导游', 'G', 'channel:rebateobject', '返利对象', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (290, '普通用户', '1', 'role:type', '角色类型', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (291, '供应商', '2', 'role:type', '角色类型', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (300, '即时解冻', '1', 'channel:rebateSettlement', '返利结算方式', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (301, '周期解冻', '0', 'channel:rebateSettlement', '返利结算方式', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (310, '定期返', '1', 'channel:rebateCycleType', '返利周期类型', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (311, '按月按天返', '2', 'channel:rebateCycleType', '返利周期类型', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (330, '天返', 'DAY', 'channel:rebateCycle', '返利结算周期', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (331, '周返', 'WEEK', 'channel:rebateCycle', '返利结算周期', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (332, '月返', 'MONTH', 'channel:rebateCycle', '返利结算周期', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (333, '年返', 'YEAR', 'channel:rebateCycle', '返利结算周期', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (350, '未通过', '1', 'channel:publishStatus', '发布状态', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (351, '已通过', '2', 'channel:publishStatus', '发布状态', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (352, '未审核', '3', 'channel:publishStatus', '发布状态', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (353, '平台', '1', 'user:loginSource', '登录来源', 1, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (354, '手机APP', '2', 'user:loginSource', '登录来源', 2, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (355, '手机和平台', '3', 'user:loginSource', '登录来源', 3, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL);

INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (356, '未启用', '0', 'strategy:status', '政策状态', 1, '2015-12-19 16:22:21', 'huxn', 'huxn', '2015-12-19 16:22:38', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (357, '已启用', '1', 'strategy:status', '政策状态', 2, '2015-12-19 16:23:21', 'huxn', 'huxn', '2015-12-19 16:23:32', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (358, '已禁用', '2', 'strategy:status', '政策状态', 3, '2015-12-19 16:26:12', 'huxn', 'huxn', '2015-12-19 16:26:23', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (370, '永久', '1', 'strategy:expiretype', '政策有效期类型', 1, '2016-1-12 16:27:25', 'huxn', 'huxn', '2016-1-12 16:27:33', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (371, '设置时长', '2', 'strategy:expiretype', '政策有效期类型', 2, '2016-1-12 16:28:25', 'huxn', 'huxn', '2016-1-12 16:28:32', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (380, '当日', '1', 'strategy:checkinexpiretype', '首检及游玩时间类型', 1, '2016-1-12 16:36:59', 'huxn', 'huxn', '2016-1-12 16:37:07', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (381, '产品有效期内', '2', 'strategy:checkinexpiretype', '首检及游玩时间类型', 2, '2016-1-12 16:37:56', 'huxn', 'huxn', '2016-1-12 16:38:03', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (382, '具体日期内', '3', 'strategy:checkinexpiretype', '首检及游玩时间类型', 2, '2016-1-12 16:37:56', 'huxn', 'huxn', '2016-1-12 16:38:03', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (390, '小时', '1', 'strategy:checkinexpireunit', '产品有效期计时单位', 1, '2016-1-12 16:43:12', 'huxn', 'huxn', '2016-1-12 16:43:19', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (391, '日', '2', 'strategy:checkinexpireunit', '产品有效期计时单位', 2, '2016-1-12 16:43:55', 'huxn', 'huxn', '2016-1-12 16:44:03', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (400, '团票', '1', 'strategy:ticketvarie', '政策票品', 1, '2016-1-12 17:10:53', 'huxn', 'huxn', '2016-1-12 17:11:01', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (401, '散票', '0', 'strategy:ticketvarie', '政策票品', 2, '2016-1-12 17:11:33', 'huxn', 'huxn', '2016-1-12 17:11:40', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (410, '线下窗口', '1', 'strategy:salesType', '政策销售端口', 1, '2016-1-12 17:22:31', 'huxn', 'huxn', '2016-1-12 17:22:46', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (411, '二维码微店', '2', 'strategy:salesType', '政策销售端口', 2, '2016-1-12 17:22:29', 'huxn', 'huxn', '2016-1-12 17:22:43', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (420, '旅行社PC端', '3', 'strategy:salesType', '政策销售端口', 3, '2016-1-12 17:26:41', 'huxn', 'huxn', '2016-1-12 17:27:09', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (421, '导游APP', '4', 'strategy:salesType', '政策销售端口', 4, '2016-1-12 17:26:44', 'huxn', 'huxn', '2016-1-12 17:27:11', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (422, '商户APP', '5', 'strategy:salesType', '政策销售端口', 5, '2016-1-12 17:26:46', 'huxn', 'huxn', '2016-1-12 17:27:13', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (423, '导游微店', '6', 'strategy:salesType', '政策销售端口', 6, '2016-1-12 17:26:48', 'huxn', 'huxn', '2016-1-12 17:27:15', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (424, '商户微店', '7', 'strategy:salesType', '政策销售端口', 7, '2016-1-12 17:26:50', 'huxn', 'huxn', '2016-1-12 17:27:17', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (425, 'OTA', '7', 'strategy:salesType', '政策销售端口', 8, '2016-1-12 17:26:50', 'huxn', 'huxn', '2016-1-12 17:27:17', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (430, '小时', '8', 'strategy:expireMode', '政策销售端口', 1, '2016-1-12 17:32:35', 'huxn', 'huxn', '2016-1-12 17:32:49', NULL, '1', NULL, NULL);
INSERT INTO `product_dict`(`id`,`label`,`value`,`type`,`description`,`sort`,`create_date`,`create_by`,`update_by`,`update_date`,`remarks`,`flag`,`data_source`,`supplier_id`) VALUES (431, '日', '2', 'strategy:expireMode', '购买时限计时单位', 2, '2016-1-12 17:32:37', 'huxn', 'huxn', '2016-1-12 17:32:51', NULL, '1', NULL, NULL);

INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('442', '首检后', '0', 'product:playTimeMode', '游玩时间模式', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('443', '游玩时间后', '1', 'product:playTimeMode', '游玩时间模式', 'admin', '1');


INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('444', '毫秒', '0', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('445', '秒', '1', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('446', '分钟', '2', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('447', '小时', '3', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('448', '天', '4', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('449', '星期', '5', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('450', '旬', '6', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('451', '月', '7', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('452', '季度', '8', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('453', '年', '9', 'common:dateTime', '时间单位', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('454', '需要检查检票次数', '0', 'product:subsidiaryType', '产品附属类型', 'admin', '1');
INSERT INTO `core_deploment`.`product_dict` (`id`, `label`, `value`, `type`, `description`, `create_by`, `flag`) VALUES ('455', '不需要检查检票次数', '1', 'product:subsidiaryType', '产品附属类型', 'admin', '1');


INSERT INTO `core_deploment`.`product_dict` VALUES (440, '全额结算', '1', 'strategy:notTotalSettlementType', '未满结算规则类型', 1, '2016-3-16 18:29:17', 'admin', 'huxn', '2016-3-16 18:29:26', NULL, '1', NULL, NULL);
INSERT INTO `core_deploment`.`product_dict` VALUES (441, '减少结算金额', '2', 'strategy:notTotalSettlementType', '未满结算规则类型', NULL, '2016-3-16 18:30:07', 'admin', 'huxn', '2016-3-16 18:30:17', NULL, '1', NULL, NULL);


COMMIT;