START TRANSACTION;

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('0', '0', '0', '0', '', '0', '0', '0', '0', '0', '0', '0', '0000-00-00 00:00:00', '0', '0000-00-00 00:00:00', '0', '1', null, null, null, null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('1', '0', '0', '财务中心', null, null, null, '6', '1', null, null, 'JQ', '2015-11-26 18:23:43', null, '2015-12-07 10:19:30', '数据初始化', '1', null, '&#xe619;', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('2', '1', '1', '地接社统计', '/report/resellerOperate/getSaleRebateData', '', '', '1', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('3', '1', '1', '销售统计', 'report1/resellerOperate/querySellReport', '', '', '2', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('4', '1', '1', '线上渠道报表', 'report1/newfinaceTicket/statisticsByDistributionByFromtype', '', '', '3', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:14:02', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('5', '1', '1', '线下售票总计', 'report1/newticketStatistics/getTicketStatisticsAll', '', '', '4', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:14:02', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('6', '1', '1', '地接社部门订单统计报表', 'report1/newDepartTicketDay/getDepartTicketDay?typeinfo=2', '', '', '5', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:14:02', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('7', '1', '1', '导游订单统计报表', 'report1/newDepartTicketDay/getDepartTicketDay?typeinfo=3', '', '', '6', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:14:02', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('8', '1', '1', '委托应收(代售)', 'report1/newfhbch-report/jointTicketBookingReport?typeinfo=1', '', '', '7', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:14:02', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('9', '1', '1', '委托应收', 'report1/newfhbch-report/jointTicketBookingReport?typeinfo=2', '', '', '8', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('10', '1', '1', '代售应付', 'report1/newfhbch-report/jointTicketBookingReport?typeinfo=3', '', '', '9', '1', '', '', 'JQ', '2015-12-06 19:40:07', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('11', '0', '0', '票务中心', '', null, '1', '1', '1', null, null, 'JQ', '2015-11-26 18:23:43', null, '2015-12-07 10:19:30', '数据初始化', '1', '1', '&#xe607;', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('12', '11', '11', '演艺票售票', '/ticket/seat/index', '', '', '1', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('13', '11', '11', '演艺预占座订单列表', '', '', '', '2', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('14', '11', '11', '门票售票', '/ticket/sale/index', '', '', '3', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('15', '11', '11', '积分票售票', '/integralTicket/sale/index', '', '', '4', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('16', '11', '11', '特价票出票', '/specialVoucher/specialVoucherTicketList', '', '', '5', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('17', '11', '11', '特价票凭证管理', '/specialVoucher/specialVoucherList', '', '', '6', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('18', '11', '11', '免票出票', '/freeVoucher/freeVoucherTicketList', '', '', '7', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('19', '11', '11', '免票凭证管理', '/freeVoucher/freeVoucherList', '', '', '8', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('20', '11', '11', '特种票模板列表', '/voucher/list', '', '', '9', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('21', '11', '11', '退票审核', '/ticket/refundList', '', '', '10', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('22', '11', '11', '我的退票审核结果', '/ticket/refundResultList', '', '', '11', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('23', '0', '0', '订单中心', '', null, null, '2', '1', null, '1', 'JQ', '2015-11-26 18:23:43', null, '2015-12-07 10:19:30', '数据初始化', '1', null, '&#xe60c;', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('24', '23', '23', '线下订单统计', '/orders/biz/selectOutLineOrdersList?is_online=0', '', '', '1', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('25', '23', '23', '我的线下订单统计', '/orders/biz/selectOutLineOrdersList?user=myList', '', '', '2', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('26', '23', '23', '线上订单统计', '/orders/biz/selectOutLineOrdersList?is_online=1', '', '', '3', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('27', '23', '23', '当日售票员统计', '', '', '', '4', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('28', '23', '23', '积分订单统计', '/orders/biz/selectOutLineOrdersList?ticketCategory\r\n=4', null, null, '5', '1', null, null, 'JQ', '2015-11-26 18:23:43', null, '2015-12-07 10:10:31', '数据初始化', '1', null, null, '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('29', '0', '0', '产品中心', '', null, null, '3', '1', null, null, 'JQ', '2015-11-26 18:23:43', null, '2015-12-07 10:19:30', '数据初始化', '1', null, '&#xe609;', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('30', '29', '29', '票型列表', '/product/ticketType/index', '', '', '1', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('31', '29', '29', '产品列表', '/product/list?type=1', '', '', '2', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('32', '29', '29', '积分规则列表', '/product/rulesIntegral/index', '', '', '4', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('33', '29', '29', '积分产品列表', '/product/list?type=3', '', '', '5', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('34', '29', '29', '普通票联票子票列表', '/product/joinTicket/normalJoinTicketList', '', '', '6', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('35', '29', '29', '积分票联票子票列表', '', '', '', '7', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('36', '29', '29', '加点返利景区关联表', '', '', '', '8', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('37', '29', '29', '产品加点返关系表', '/profitRebateRuleProduct/queryProductList', '', '', '9', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('38', '29', '29', '退换票规则列表', '/ticketBackRule/queryTicketBackRuleList', '', '', '10', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('39', '0', '0', '渠道中心', '', '', '', '4', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '&#xe60e;', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('40', '39', '39', '渠道列表', '/fromtype/channel/index', '', '', '1', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('41', '39', '39', '分销商管理', '/fromtype/reseller/queryResellerList', '', '', '2', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('42', '39', '39', '导游管理\r\n', '/fromtype/reseller/queryGuideList', null, null, '2', '1', null, null, 'JQ', '2015-12-01 14:37:36', null, '2015-12-07 10:10:31', '数据初始化', '1', null, null, '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('43', '39', '39', '协议单位列表', '/protocolUnit/protocolUnitList', '', '', '12', '1', '', '', 'JQ', '2015-11-30 13:57:41', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('44', '39', '39', '政策列表(审核)', '/fromtype/strategy/queryStrategyList', '', '', '3', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('45', '39', '39', '政策列表(发布)', '/fromtype/strategy/makeStrategyList', '', '', '4', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('46', '0', '0', '企业中心', '', '', '', '5', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '&#xe60b;', '数据初始化', null);

INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('47', '46', '46', '企业基础设置', '/user/enterpriseIndex', '', '', '1', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('48', '46', '46', '景区管理', '/scenic/list', '', '', '2', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('49', '46', '46', '剧场管理', '/screen/list', '', '', '3', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('50', '46', '46', '检票点管理', '/checkInSite/list', '', '', '4', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('51', '46', '46', '检票设备管理', '/checkInDevice/list', '', '', '5', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('52', '46', '46', '售票点管理', '/enterprise/point/index', '', '', '6', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('53', '46', '46', '直销工具管理', '/enterprise/tool/index', '', '', '7', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('54', '46', '46', '部门管理', '/department/pagelistRole', '', '', '8', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:19:30', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('55', '46', '46', '员工管理', '/enterprise/customer/index', '', '', '9', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('56', '46', '46', '修改密码', '/user/changePs', '', '', '10', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:10:31', '数据初始化', '1', '', '', '数据初始化', null);
INSERT INTO `sys_menu` (`id`,`parent_id`,`parent_ids`,`name`,`href`,`target`,`icon`,`sort`,`is_show`,`is_activiti`,`permission`,`create_by`,`create_date`,`update_by`,`update_date`,`remarks`,`del_flag`,`position`,`style`,`data_source`,`supplier_id`) VALUES ('57', '46', '46', '操作日志', '/log/pagelistLog', '', '', '11', '1', '', '', 'JQ', '2015-11-26 18:23:43', '', '2015-12-07 10:16:42', '数据初始化', '1', '', '', '数据初始化', null);

COMMIT;